sudo: required
dist: xenial
language: python
python: 3.7

install:
  - pwd
  - ls
  - mkdir bin
  - sudo apt update
  - sudo apt install docker.io -y
  - sudo docker build --rm -f "Dockerfile" -t driplet:latest .
  - pip install requests

before_script:
  - sudo docker run -p 3141:3141 driplet &

script:
  - python backend/tests/acc_create.py