sudo: required
dist: xenial
language: python
python: 3.7

install:
  - sudo apt update
  - sudo apt install docker.io -y
  - sudo docker build --rm -f "Dockerfile" -t driplet:latest .
  - mkdir ~/data
  - pip install requests pymongo

before_script:
  - sudo docker run -d -p 27017:27017 -v ~/data:/data/db mongo
  - python mongo_init.py
  - sudo docker run --network=host driplet &

script:
  - sleep 5 