sudo: required
dist: bionic
language: python

install:
  - sudo apt update
  - sudo apt install docker.io -y
  - sudo docker build --rm -f "Dockerfile" -t driplet:latest .

before_script:
  - sudo docker run -d -p 3141:3141 driplet

script:
  - ./test.sh