steps:

- name: 'docker.io/library/python:3.7'
   args: ['-m', 'pip', 'install' '-r', 'requirements.txt']

- name: 'ubuntu'
   args: ['cd', 'backend/']

- name:  'docker.io/library/python:3.7'
   args: ['app.py']